- name: Install epel repository
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: Install httpd-tools package
  yum:
    name: httpd-tools
    state: present
    update_cache: yes

- name: Install squid package
  yum:
    name: squid
    state: present
    update_cache: yes

- name: Enable and start squid service
  systemd:
    name: squid
    state: started
    enabled: yes

- import_tasks: configure_squid.yml
  tags:
    - configure_squid
  notify:
    - Restart squid

- import_tasks: auth_squid.yml
  when: set_auth == True
  tags:
    - configure_auth

- import_tasks: anonymize_squid.yml
  when: anonymize == True
  tags:
    - anonymize

- import_tasks: restrict_sites.yml
  when: restrict_sites == True
  tags:
    - restrict_sites

- import_tasks: restrict_keywords.yml
  when: restrict_keywords == True
  tags:
    - restrict_keywords
